import { readFileSync, statSync } from 'node:fs';
import { resolve, relative, isAbsolute } from 'node:path';
import { matchGlob, matchGlobs } from '../families/glob.mjs';

const files = new Map();
function json(path, fallback) {
  try {
    const stat = statSync(path);
    const key = `${stat.mtimeMs}:${stat.ctimeMs}:${stat.size}:${stat.ino}`;
    const cached = files.get(path);
    if (cached?.key === key) return cached.value;
    const value = JSON.parse(readFileSync(path, 'utf8'));
    files.set(path, { key, value });
    return value;
  } catch { files.delete(path); return fallback; }
}

const rule = {
  meta: {
    type: 'problem',
    docs: { description: 'Use generated family references instead of block ID strings.' },
    schema: [{ type: 'object', properties: {
      bareIds: { type: 'array', items: { type: 'string' }, uniqueItems: true },
      minBareLength: { type: 'integer', minimum: 1 },
      allow: { type: 'array', items: { type: 'string' } },
      reportUnusedBaseline: { type: 'boolean' },
    }, additionalProperties: false }],
    messages: {
      literal: 'Use a generated family reference instead of the block ID literal {{id}}.',
      unusedBaseline: 'The no-block-id-literal baseline for {{file}} can be lowered from {{allowed}} to {{count}}.',
    },
  },
  create(context) {
    const root = resolve(context.cwd ?? context.getCwd?.() ?? process.cwd());
    const filename = context.filename ?? context.getFilename();
    if (filename === '<input>' || filename === '<text>') return {};
    const path = relative(root, resolve(root, filename)).replaceAll('\\', '/');
    if (isAbsolute(path) || path === '..' || path.startsWith('../')) return {};
    const options = context.options?.[0] ?? {};
    const config = json(resolve(root, '.blocks/config.json'), {});
    const families = Array.isArray(config?.families) ? config.families : [];
    const skipped = [
      '.blocks/index.json', '.blocks/config.json', '.blocks/baseline.json',
      '.blocks/manifests/**',
      ...families.flatMap((family) => [family.manifests, family.contract, ...(family.generators ?? []), family.registry?.out]),
      ...(config?.generators ?? []),
    ];
    const source = context.sourceCode ?? context.getSourceCode();
    if (source.text.split(/\r?\n/, 1)[0].includes('generated by block-beaver from ') || skipped.some((pattern) => typeof pattern === 'string' && matchGlob(path, pattern)) || ((options.allow?.length ?? 0) > 0 && matchGlobs([path], options.allow).length > 0)) return {};
    const manifests = json(resolve(root, '.blocks/index.json'), []);
    const qualified = new Set(), bare = new Set();
    const bareFamilies = new Set(options.bareIds ?? []);
    for (const manifest of Array.isArray(manifests) ? manifests : []) {
      if (typeof manifest?.family !== 'string' || typeof manifest.id !== 'string') continue;
      qualified.add(`${manifest.family}:${manifest.id}`);
      qualified.add(`block:${manifest.family}:${manifest.id}`);
      if (bareFamilies.has(manifest.family) && manifest.id.length >= (options.minBareLength ?? 3)) bare.add(manifest.id);
    }
    const baseline = json(resolve(root, '.blocks/baseline.json'), {});
    const rawAllowed = baseline?.lint?.['no-block-id-literal']?.[path];
    const allowed = Number.isSafeInteger(rawAllowed) && rawAllowed >= 0 ? rawAllowed : 0;
    let count = 0;
    function visit(node, value) {
      if (typeof value !== 'string' || (!qualified.has(value) && !bare.has(value))) return;
      count++;
      if (count > allowed) context.report({ node, messageId: 'literal', data: { id: value } });
    }
    return {
      Literal(node) { visit(node, node.value); },
      TemplateLiteral(node) { if (!node.expressions.length) visit(node, node.quasis[0]?.value.cooked); },
      'Program:exit'(node) {
        if (options.reportUnusedBaseline && count < allowed) context.report({ node, messageId: 'unusedBaseline', data: { file: path, allowed, count } });
      },
    };
  },
};

const plugin = { rules: { 'no-block-id-literal': rule }, configs: {} };
plugin.configs.recommended = { plugins: { 'block-beaver': plugin }, rules: { 'block-beaver/no-block-id-literal': 'error' } };
export const rules = plugin.rules;
export const configs = plugin.configs;
export default plugin;
