import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm, utimes } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import plugin from '../src/eslint/index.mjs';

async function fixture(t) {
  const root = await mkdtemp(join(tmpdir(), 'block-beaver-lint-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(join(root, '.blocks'));
  const config = { families: [{ id: 'widget', contract: 'families/widget.family.ts', manifests: 'blocks/**/*.widget.ts', generators: ['generators/widget.ts'] }], generators: ['generators/all.ts'] };
  await writeFile(join(root, '.blocks/config.json'), JSON.stringify(config));
  await writeFile(join(root, '.blocks/index.json'), JSON.stringify([{ family: 'widget', id: 'alpha' }, { family: 'widget', id: 'ab' }, { family: 'gadget', id: 'beta' }]));
  return root;
}

// Exercise ESLint's public rule context/listener interface; no ESLint runtime dependency.
function lint(root, values, options = {}, filename = 'src/main.ts', text = '') {
  const reports = [];
  const listeners = plugin.rules['no-block-id-literal'].create({
    cwd: root, filename: join(root, filename), options: [options],
    sourceCode: { text }, report(report) { reports.push(report); },
  });
  for (const value of values) {
    const node = typeof value === 'object' ? value : { type: 'Literal', value };
    listeners[node.type]?.(node);
  }
  listeners['Program:exit']?.({ type: 'Program' });
  return reports;
}
const template = (text, expressions = []) => ({ type: 'TemplateLiteral', quasis: [{ value: { cooked: text } }], expressions });

test('flat plugin recommended config registers the dependency-free public rule', () => {
  assert.equal(plugin.configs.recommended.plugins['block-beaver'], plugin);
  assert.equal(plugin.configs.recommended.rules['block-beaver/no-block-id-literal'], 'error');
});

test('qualified refs are exact matches; bare IDs require per-family opt-in and minimum length', async (t) => {
  const root = await fixture(t);
  const values = ['widget:alpha', 'block:widget:alpha', 'gadget:beta', 'alpha', 'ab', 'beta', 'prefix widget:alpha', 'widget:missing', 42];
  assert.equal(lint(root, values).length, 3);
  assert.equal(lint(root, values, { bareIds: ['widget'] }).length, 4);
  assert.equal(lint(root, values, { bareIds: ['widget'], minBareLength: 2 }).length, 5);
});

test('static cooked template strings are flagged while dynamic templates are ignored', async (t) => {
  const root = await fixture(t);
  assert.equal(lint(root, [template('widget:alpha'), template('widget:alpha', [{}]), template('widget:missing'), template(null)]).length, 1);
});

test('generated headers, manifests, contracts, generators, and allowed globs are skipped', async (t) => {
  const root = await fixture(t);
  for (const filename of ['blocks/a.widget.ts', 'blocks/nested/a.widget.ts', 'families/widget.family.ts', 'generators/widget.ts', 'generators/all.ts', '.blocks/manifests/old.json', '.blocks/index.json']) {
    assert.equal(lint(root, ['widget:alpha'], {}, filename).length, 0, filename);
  }
  assert.equal(lint(root, ['widget:alpha'], {}, 'src/generated.ts', '// generated by block-beaver from blocks/*.ts; do not edit\n').length, 0);
  assert.equal(lint(root, ['widget:alpha'], { allow: ['src/**/*.{ts,js}'] }).length, 0);
  assert.equal(lint(root, ['widget:alpha'], { allow: ['src/**', '!src/main.ts'] }).length, 1);
  assert.equal(lint(root, ['widget:alpha'], {}, 'src/main.ts', '// ordinary source\n').length, 1);
});

test('baseline suppresses only allowed occurrences and reports opportunities to lower counts', async (t) => {
  const root = await fixture(t);
  await writeFile(join(root, '.blocks/baseline.json'), JSON.stringify({ lint: { 'no-block-id-literal': { 'src/main.ts': 2 } } }));
  assert.equal(lint(root, ['widget:alpha', 'widget:alpha']).length, 0);
  const excess = lint(root, ['widget:alpha', 'widget:alpha', 'widget:alpha']);
  assert.equal(excess.length, 1);
  assert.equal(excess[0].messageId, 'literal');
  const unused = lint(root, ['widget:alpha'], { reportUnusedBaseline: true });
  assert.equal(unused.length, 1);
  assert.equal(unused[0].messageId, 'unusedBaseline');
  assert.deepEqual(unused[0].data, { file: 'src/main.ts', allowed: 2, count: 1 });
  assert.equal(lint(root, [], {}).length, 0);
});

test('cached files reload after index, config and baseline edits', async (t) => {
  const root = await fixture(t);
  assert.equal(lint(root, ['widget:alpha']).length, 1);
  const index = join(root, '.blocks/index.json');
  await writeFile(index, JSON.stringify([{ family: 'widget', id: 'fresh' }]));
  await utimes(index, new Date(), new Date(Date.now() + 5000));
  assert.equal(lint(root, ['widget:alpha', 'widget:fresh']).length, 1);
  await writeFile(join(root, '.blocks/config.json'), JSON.stringify({ families: [{ id: 'widget', manifests: 'src/**' }] }));
  assert.equal(lint(root, ['widget:fresh']).length, 0);
  await writeFile(join(root, '.blocks/config.json'), '{}');
  await writeFile(join(root, '.blocks/baseline.json'), JSON.stringify({ lint: { 'no-block-id-literal': { 'src/main.ts': 1 } } }));
  assert.equal(lint(root, ['widget:fresh']).length, 0);
  await writeFile(join(root, '.blocks/baseline.json'), '{}');
  assert.equal(lint(root, ['widget:fresh']).length, 1);
});

test('missing or corrupt optional data is tolerated, invalid baseline values grant no allowance', async (t) => {
  const root = await fixture(t);
  await writeFile(join(root, '.blocks/baseline.json'), JSON.stringify({ lint: { 'no-block-id-literal': { 'src/main.ts': -2 } } }));
  assert.equal(lint(root, ['widget:alpha']).length, 1);
  await writeFile(join(root, '.blocks/index.json'), 'broken');
  assert.equal(lint(root, ['widget:alpha']).length, 0);
  await rm(join(root, '.blocks/index.json'));
  assert.equal(lint(root, ['widget:alpha']).length, 0);
});
