import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile, rm, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { applyGeneration, checkGeneration, planGeneration } from '../src/families/generate.mjs';

const NOW = new Date('2026-10-01T12:00:00Z');

async function repo(t, files = {}) {
  const root = await mkdtemp(join(tmpdir(), 'block-beaver-gen-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  for (const [path, text] of Object.entries(files)) {
    await mkdir(dirname(join(root, path)), { recursive: true });
    await writeFile(join(root, path), text);
  }
  return root;
}

const family = (id, { floor = 0, generators = ['registry'], registry, manifests = `blocks/${id}s/*.ts`, extra = {} } = {}) => ({
  id, implementation: ['module', 'none'], fields: { type: 'object', shape: {} }, links: [], generators, hasCheck: false, floor,
  config: { id, contract: `blocks/${id}.family.ts`, manifests, ...(registry === null ? {} : { registry: registry ?? { out: `src/generated/${id}.ts` } }), ...extra },
});
const manifest = (familyId, id, { exportName = 'default', path, hash, value } = {}) => ({
  family: familyId, id, ref: `${familyId}:${id}`, graphId: `block:${familyId}:${id}`,
  path: path ?? `blocks/${familyId}s/${id}.ts`, exportName, hash: hash ?? `sha256:${familyId}-${id}`,
  value: value ?? { id, family: familyId, version: 1, name: id, description: id, rationale: 'because', implementation: { kind: 'none' } },
});

/** Fake of the public loader seam: returns a canned FamilyLoadResult and records every call. */
function fakeLoader({ families = [], manifests = [], generators = [], diagnostics = [], outputs = {}, loadedFiles = [] } = {}) {
  const calls = [];
  const load = async (args) => {
    calls.push(args);
    const result = { key: 'fake', families, manifests, generators, loadedFiles, diagnostics };
    if (args.generate) {
      result.outputs = args.generate.keys.map((key) => {
        const out = outputs[key];
        return typeof out === 'object' && out?.diagnostic ? { key, diagnostic: out.diagnostic } : { key, content: typeof out === 'function' ? out(args.generate) : out };
      });
    }
    return result;
  };
  load.calls = calls;
  return load;
}

const plan = (root, loader, extra = {}) => planGeneration({ root, config: {}, graph: { nodes: [], hashes: {} }, paths: [], label: null, now: NOW, loadFamilies: loader, ...extra });

test('a family that asks for a registry gets a headered typed module with preserved import styles', async (t) => {
  const root = await repo(t);
  const loader = fakeLoader({
    families: [family('gizmo')],
    manifests: [manifest('gizmo', 'b'), manifest('gizmo', 'a', { exportName: 'aManifest' })],
  });
  const result = await plan(root, loader);
  assert.deepEqual(result.diagnostics, []);
  assert.equal(result.outputs.length, 1);
  const [registry] = result.outputs;
  assert.equal(registry.key, 'registry:gizmo');
  assert.equal(registry.out, 'src/generated/gizmo.ts');
  assert.equal(registry.status, 'missing');
  assert.equal(registry.current, null);
  assert.equal(registry.expected, [
    '// generated by block-beaver from blocks/gizmos/*.ts; do not edit',
    "import { createRegistry } from 'block-beaver/kernel';",
    "import { aManifest as m0 } from '../../blocks/gizmos/a';",
    "import m1 from '../../blocks/gizmos/b';",
    '',
    "export const gizmoRegistry = createRegistry('gizmo', [m0, m1] as const);",
    "export type GizmoManifest = (typeof gizmoRegistry)['all'][number];",
    "export type GizmoId = GizmoManifest['id'];",
    '',
  ].join('\n'));
});

const custom = (path, { out, inputs = [], cache = true, closureHash = 'c1', family: owner } = {}) => ({ key: `custom:${path}`, source: 'custom', ...(owner ? { family: owner } : {}), path, out, inputs, cache, closureHash });
const byKey = (result) => Object.fromEntries(result.outputs.map((output) => [output.key, output]));
const codes = (result) => result.diagnostics.map((item) => item.code);
const generateCalls = (loader) => loader.calls.filter((call) => call.generate);
const listing = async (root) => (await readdir(root, { recursive: true })).map(path => path.replaceAll('\\', '/')).sort();
const kernelOnly = (text) => text.split('\n').filter((line) => line.startsWith('import ')).length;

test('a repository with no families plans nothing and touches nothing', async (t) => {
  const root = await repo(t);
  const result = await plan(root, fakeLoader());
  assert.deepEqual(result, { outputs: [], diagnostics: [], cacheUpdate: null });
  assert.deepEqual(checkGeneration(result), []);
  assert.deepEqual(await applyGeneration(root, result), { written: [], diagnostics: [] });
  assert.deepEqual(await listing(root), []);
});

test('an empty family still emits a registry that type-checks', async (t) => {
  const root = await repo(t);
  const { outputs } = await plan(root, fakeLoader({ families: [family('gizmo')] }));
  assert.match(outputs[0].expected, /createRegistry\('gizmo', \[\] as const\);/);
  assert.equal(kernelOnly(outputs[0].expected), 1);
});

test('registry export names, import extensions and long lists follow the family configuration', async (t) => {
  const root = await repo(t);
  const loader = fakeLoader({
    families: [family('kebab-case-thing', { registry: { out: 'gen/reg.ts', exportName: 'things', importExtension: '.js' } }), family('plain', { registry: { out: 'gen/plain.ts', importExtension: '.ts' } })],
    manifests: [
      manifest('kebab-case-thing', 'a', { path: 'blocks/x/a.mts' }),
      manifest('kebab-case-thing', 'b', { path: 'blocks/x/b.ts' }),
      ...Array.from({ length: 30 }, (_, index) => manifest('plain', `item-${String(index).padStart(2, '0')}`, { path: `blocks/p/item-${String(index).padStart(2, '0')}.ts` })),
    ],
  });
  const { outputs, diagnostics } = await plan(root, loader);
  assert.deepEqual(diagnostics, []);
  const [js, ts] = outputs;
  assert.match(js.expected, /import m0 from '\.\.\/blocks\/x\/a\.mjs';/);
  assert.match(js.expected, /import m1 from '\.\.\/blocks\/x\/b\.js';/);
  assert.match(js.expected, /export const things = createRegistry\('kebab-case-thing', \[m0, m1\] as const\);/);
  assert.match(js.expected, /export type KebabCaseThingManifest = \(typeof things\)\['all'\]\[number\];/);
  assert.match(js.expected, /export type KebabCaseThingId = KebabCaseThingManifest\['id'\];/);
  assert.match(ts.expected, /import m0 from '\.\.\/blocks\/p\/item-00\.ts';/);
  assert.match(ts.expected, /export const plainRegistry = createRegistry\('plain', \[\n  m0,\n  m1,\n/);
  assert.match(ts.expected, /\n  m29,\n\] as const\);\n/);
});

test('a registry that cannot be written or imported is a diagnostic, not a crash', async (t) => {
  const root = await repo(t);
  const noOut = family('gizmo', { registry: null });
  const { outputs, diagnostics } = await plan(root, fakeLoader({
    families: [noOut, family('widget', { registry: { out: 'gen/widget.ts' } })],
    manifests: [manifest('widget', 'a', { exportName: 'not-an-identifier' })],
  }));
  assert.deepEqual(outputs, []);
  assert.deepEqual(diagnostics.map((item) => [item.rule, item.code, item.family]), [['config-valid', 'registry-out-missing', 'gizmo'], ['family-drift', 'generator-failed', 'widget']]);
  assert.match(diagnostics[1].message, /widget:a/);
});

test('outputs come in the fixed order whatever order the loader reports them', async (t) => {
  const root = await repo(t);
  const loader = fakeLoader({
    families: [family('gizmo', { generators: ['registry', 'index'] }), family('widget', { floor: 1, generators: ['history', 'registry'] })],
    generators: [
      custom('gen/global.ts', { out: 'gen/global-extra.ts' }),
      custom('gen/widget.ts', { out: 'gen/widget-extra.ts', family: 'widget' }),
      custom('gen/gizmo.ts', { out: 'gen/gizmo-extra.ts', family: 'gizmo' }),
    ],
    outputs: { 'custom:gen/global.ts': 'g', 'custom:gen/widget.ts': 'w', 'custom:gen/gizmo.ts': 'z' },
  });
  const result = await plan(root, loader, { extraOutputs: [{ key: 'view', out: '.blocks/view/module.mjs', render: () => 'export {};' }] });
  assert.deepEqual(result.diagnostics, []);
  assert.deepEqual(result.outputs.map((output) => output.key), ['registry:gizmo', 'registry:widget', 'index', 'custom:gen/gizmo.ts', 'custom:gen/widget.ts', 'custom:gen/global.ts', 'view', 'history']);
});

test('the index is a bare array of authored manifests ordered by family then id', async (t) => {
  const root = await repo(t);
  const authored = { version: 1, id: 'b', family: 'gizmo', zebra: true, name: 'B', description: 'd', rationale: 'r', implementation: { kind: 'none' }, apple: { z: 1, a: 2 } };
  const loader = fakeLoader({
    families: [family('gizmo', { generators: ['index'], registry: null }), family('widget', { floor: 1, generators: ['index'], registry: null })],
    manifests: [manifest('widget', 'a'), manifest('gizmo', 'b', { value: authored }), manifest('gizmo', 'a')],
  });
  const { outputs } = await plan(root, loader);
  assert.equal(outputs.length, 1);
  assert.equal(outputs[0].out, '.blocks/index.json');
  const parsed = JSON.parse(outputs[0].expected);
  assert.ok(Array.isArray(parsed));
  assert.deepEqual(parsed.map((item) => `${item.family}:${item.id}`), ['gizmo:a', 'gizmo:b', 'widget:a']);
  assert.equal(outputs[0].expected, `${JSON.stringify(parsed, null, 2)}\n`);
  assert.deepEqual(Object.keys(parsed[1]), Object.keys(authored), 'authored key order is preserved');
  assert.ok(!outputs[0].expected.includes('generated by block-beaver'), 'JSON carries no header');
  const empty = await plan(root, fakeLoader({ families: [family('gizmo', { generators: ['index'], registry: null })] }));
  assert.equal(empty.outputs[0].expected, '[]\n');
});

test('each output kind gets its own header style, LF endings and a trailing newline', async (t) => {
  const root = await repo(t);
  const outs = { ts: 'gen/a.ts', mjs: 'gen/a.mjs', css: 'gen/a.css', md: 'gen/a.md', html: 'gen/a.html', json: 'gen/a.json', crlf: 'gen/crlf.ts', empty: 'gen/empty.ts' };
  const inputs = ['x/**/*.ts', 'y--z/*.ts'];
  const loader = fakeLoader({
    generators: Object.entries(outs).map(([name, out]) => custom(name, { out, inputs })),
    outputs: { 'custom:ts': 'body', 'custom:mjs': 'body\n', 'custom:css': 'body', 'custom:md': 'body', 'custom:html': 'body', 'custom:json': '{"a":1}', 'custom:crlf': 'a\r\nb\rc', 'custom:empty': '' },
  });
  const result = await plan(root, loader);
  assert.deepEqual(result.diagnostics, []);
  const expected = Object.fromEntries(result.outputs.map((output) => [output.key.slice('custom:'.length), output.expected]));
  assert.equal(expected.ts, '// generated by block-beaver from x/**/*.ts, y--z/*.ts; do not edit\nbody\n');
  assert.equal(expected.mjs, '// generated by block-beaver from x/**/*.ts, y--z/*.ts; do not edit\nbody\n');
  assert.equal(expected.css, '/* generated by block-beaver from x/**\\/*.ts, y--z/*.ts; do not edit */\nbody\n');
  assert.equal(expected.md, '<!-- generated by block-beaver from x/**/*.ts, y-\\-z/*.ts; do not edit -->\nbody\n');
  assert.equal(expected.html, expected.md);
  assert.equal(expected.json, '{"a":1}\n');
  assert.equal(expected.crlf, '// generated by block-beaver from x/**/*.ts, y--z/*.ts; do not edit\na\nb\nc\n');
  assert.equal(expected.empty, '// generated by block-beaver from x/**/*.ts, y--z/*.ts; do not edit\n');
});

test('a header can never be broken out of, and bad output is refused rather than written', async (t) => {
  const root = await repo(t);
  const loader = fakeLoader({
    generators: [
      custom('injected', { out: 'gen/injected.ts', inputs: ['a\nconsole.log(1)//'] }),
      custom('separators', { out: 'gen/separators.ts', inputs: [`a${String.fromCharCode(0x2028)}b${String.fromCharCode(0x2029)}c`] }),
      custom('badjson', { out: 'gen/bad.json' }),
      custom('notstring', { out: 'gen/notstring.ts' }),
      custom('text', { out: 'gen/readme.txt' }),
    ],
    outputs: { 'custom:injected': 'x', 'custom:separators': 'x', 'custom:badjson': '{nope', 'custom:notstring': 5, 'custom:text': 'x' },
  });
  const result = await plan(root, loader);
  const lines = byKey(result)['custom:injected'].expected.split('\n');
  assert.equal(lines[0], '// generated by block-beaver from a console.log(1)//; do not edit');
  assert.equal(byKey(result)['custom:separators'].expected.split('\n').length, 3);
  assert.deepEqual(result.outputs.map((output) => output.key), ['custom:injected', 'custom:separators']);
  assert.deepEqual(result.diagnostics.map((item) => [item.code, item.file]).sort(), [['generator-failed', 'gen/bad.json'], ['generator-failed', 'gen/notstring.ts'], ['output-unsafe', 'gen/readme.txt']]);
});

test('unsafe or input-overwriting output paths are rejected before any generator runs', async (t) => {
  const root = await repo(t);
  const outs = ['../escape.ts', '/abs.ts', 'a//b.ts', 'a/./b.ts', 'node_modules/x.ts', 'pkg/node_modules/x.ts', '.git/x.ts', '.blocks/cache/x.json', '.blocks/cache/generators.json', '.blocks/config.json', 'blocks/gizmos/a.ts', 'blocks/gizmo.family.ts', 'gen/self.ts'];
  const loader = fakeLoader({
    families: [family('gizmo', { generators: [] })],
    manifests: [manifest('gizmo', 'a')],
    generators: outs.map((out, index) => custom(`gen/${index === outs.length - 1 ? 'self' : `g${index}`}.ts`, { out })),
    outputs: {},
  });
  const result = await plan(root, loader);
  assert.deepEqual(result.outputs, []);
  assert.equal(result.diagnostics.length, outs.length);
  assert.ok(result.diagnostics.every((item) => item.code === 'output-unsafe' && item.severity === 'error'));
  assert.equal(generateCalls(loader).length, 0, 'unsafe generators never run');
});

test('every claim on one output is an error, nobody wins, and colliding generators do not run', async (t) => {
  const root = await repo(t);
  const loader = fakeLoader({
    families: [family('gizmo', { registry: { out: 'src/shared.ts' } }), family('widget', { floor: 1, generators: ['index'] })],
    generators: [custom('gen/one.ts', { out: 'src/shared.ts' }), custom('gen/two.ts', { out: 'SRC/Shared.ts' }), custom('gen/fine.ts', { out: 'src/fine.ts' })],
    outputs: { 'custom:gen/fine.ts': 'ok' },
  });
  const result = await plan(root, loader, { extraOutputs: [{ key: 'view', out: '.blocks/index.json', render: () => '[]' }] });
  const collisions = result.diagnostics.filter((item) => item.code === 'output-collision');
  assert.equal(collisions.length, 2);
  assert.ok(['registry:gizmo', 'custom:gen/one.ts', 'custom:gen/two.ts'].every((key) => collisions[0].message.includes(key)));
  assert.ok(['index', 'view'].every((key) => collisions[1].message.includes(key)));
  assert.deepEqual(result.outputs.map((output) => output.key), ['custom:gen/fine.ts']);
  assert.deepEqual(generateCalls(loader).map((call) => call.generate.keys), [['custom:gen/fine.ts']]);
});

test('writing, checking and re-planning are byte-stable and check writes nothing', async (t) => {
  const root = await repo(t);
  const loader = fakeLoader({ families: [family('gizmo', { generators: ['registry', 'index'] })], manifests: [manifest('gizmo', 'a')] });
  const first = await plan(root, loader);
  assert.deepEqual(first.outputs.map((output) => output.status), ['missing', 'missing']);
  assert.deepEqual(checkGeneration(first).map((item) => [item.rule, item.code, item.file, item.family]), [
    ['family-drift', 'output-missing', 'src/generated/gizmo.ts', 'gizmo'],
    ['family-drift', 'output-missing', '.blocks/index.json', undefined],
  ]);
  assert.deepEqual(await listing(root), [], 'check wrote nothing');

  const applied = await applyGeneration(root, first);
  assert.deepEqual(applied.written, ['src/generated/gizmo.ts', '.blocks/index.json']);
  const bytes = await Promise.all(first.outputs.map((output) => readFile(join(root, output.out), 'utf8')));
  assert.deepEqual(bytes, first.outputs.map((output) => output.expected));

  const second = await plan(root, loader);
  assert.deepEqual(second.outputs.map((output) => output.status), ['fresh', 'fresh']);
  assert.deepEqual(checkGeneration(second), []);
  assert.deepEqual((await applyGeneration(root, second)).written, []);
  assert.deepEqual(await Promise.all(first.outputs.map((output) => readFile(join(root, output.out), 'utf8'))), bytes);
});

test('a modified or deleted generated file is drift, and gen restores it', async (t) => {
  const root = await repo(t);
  const loader = fakeLoader({ families: [family('gizmo')], manifests: [manifest('gizmo', 'a')] });
  await applyGeneration(root, await plan(root, loader));
  const path = join(root, 'src/generated/gizmo.ts');
  const good = await readFile(path, 'utf8');

  await writeFile(path, good.replace('createRegistry(', 'tampered('));
  const stale = await plan(root, loader);
  assert.equal(stale.outputs[0].status, 'stale');
  assert.deepEqual(checkGeneration(stale).map((item) => item.code), ['output-stale']);
  assert.match(await readFile(path, 'utf8'), /tampered/, 'check left the edit alone');
  await applyGeneration(root, stale);
  assert.equal(await readFile(path, 'utf8'), good);

  await rm(path);
  assert.deepEqual(checkGeneration(await plan(root, loader)).map((item) => item.code), ['output-missing']);
});

test('a file that block-beaver did not generate is never overwritten, but a configured JSON output is', async (t) => {
  const root = await repo(t, { 'src/generated/gizmo.ts': 'export const mine = 1;\n', 'src/generated/other.ts': '// generated by block-beaver from nowhere; do not edit\nold\n', '.blocks/index.json': '{"legacy":true}\n' });
  const loader = fakeLoader({
    families: [family('gizmo', { generators: ['registry', 'index'] }), family('widget', { floor: 1 })],
    manifests: [manifest('gizmo', 'a')],
  });
  const result = await plan(root, loader);
  const statuses = Object.fromEntries(result.outputs.map((output) => [output.key, output.status]));
  assert.deepEqual(statuses, { 'registry:gizmo': 'conflict', 'registry:widget': 'missing', index: 'stale' });
  assert.deepEqual(result.diagnostics.map((item) => [item.code, item.severity, item.file]), [['output-conflict', 'error', 'src/generated/gizmo.ts']]);
  const applied = await applyGeneration(root, result);
  assert.deepEqual(applied.written, []);
  assert.equal(await readFile(join(root, 'src/generated/gizmo.ts'), 'utf8'), 'export const mine = 1;\n');
  assert.equal(await readFile(join(root, '.blocks/index.json'), 'utf8'), '{"legacy":true}\n', 'nothing is written while any output is in error');
});

test('loader errors stop writes, but warnings do not', async (t) => {
  const root = await repo(t);
  const base = { families: [family('gizmo')], manifests: [manifest('gizmo', 'a')] };
  const error = { rule: 'manifest-valid', code: 'manifest-schema', severity: 'error', message: 'bad', file: 'blocks/gizmos/z.ts' };
  const blocked = await plan(root, fakeLoader({ ...base, diagnostics: [error] }));
  assert.deepEqual(blocked.diagnostics, [error]);
  assert.deepEqual((await applyGeneration(root, blocked)).written, []);
  assert.deepEqual(await listing(root), []);
  assert.deepEqual(checkGeneration(blocked).map((item) => item.code), ['manifest-schema', 'output-missing']);

  const warning = { ...error, severity: 'warning' };
  const allowed = await plan(root, fakeLoader({ ...base, diagnostics: [warning] }));
  assert.deepEqual((await applyGeneration(root, allowed)).written, ['src/generated/gizmo.ts']);
});

test('a throwing generator is reported once and produces no output or cache entry', async (t) => {
  const root = await repo(t, { 'data/a.json': '1' });
  const failure = { rule: 'family-drift', code: 'generator-failed', severity: 'error', message: 'boom', file: 'gen/bad.ts' };
  const loader = fakeLoader({
    generators: [custom('gen/bad.ts', { out: 'gen/bad.md', inputs: ['data/*.json'] }), custom('gen/good.ts', { out: 'gen/good.md', inputs: ['data/*.json'] })],
    outputs: { 'custom:gen/bad.ts': { diagnostic: failure }, 'custom:gen/good.ts': 'fine' },
  });
  const result = await plan(root, loader);
  assert.deepEqual(result.diagnostics, [failure]);
  assert.deepEqual(result.outputs.map((output) => output.key), ['custom:gen/good.ts']);
  assert.deepEqual(Object.keys(JSON.parse(result.cacheUpdate.content).entries), ['custom:gen/good.ts']);
});

/** A custom generator over real input files, whose output changes on every real run. */
async function cached(t, { files = { 'data/one.json': '{"n":1}', 'docs/readme.md': 'hi' }, ...options } = {}) {
  const root = await repo(t, files);
  let runs = 0;
  const info = custom('gen/table.ts', { out: 'gen/table.md', inputs: ['data/*.json'], ...options });
  const loader = fakeLoader({ generators: [info], outputs: { [info.key]: () => `run ${++runs}` } });
  const settle = async () => { const result = await plan(root, loader); await applyGeneration(root, result); return result; };
  return { root, loader, info, settle, runs: () => runs };
}

test('a custom generator is skipped while its real input globs, code and output are unchanged', async (t) => {
  const { root, loader, settle } = await cached(t);
  const first = await settle();
  assert.equal(first.outputs[0].status, 'missing');
  assert.equal(generateCalls(loader).length, 1);
  assert.equal(JSON.parse(await readFile(join(root, '.blocks/cache/generators.json'), 'utf8')).schemaVersion, 1);

  const second = await settle();
  assert.equal(second.outputs[0].status, 'cached');
  assert.equal(second.outputs[0].expected, second.outputs[0].current);
  assert.equal(second.cacheUpdate, null);
  assert.equal(generateCalls(loader).length, 1, 'no child was asked to run it');
  assert.deepEqual(checkGeneration(second), []);

  await writeFile(join(root, 'docs/readme.md'), 'changed but not an input');
  assert.equal((await settle()).outputs[0].status, 'cached');
  assert.equal(generateCalls(loader).length, 1);
});

test('changing a matched input, adding a match, changing code or editing the output reruns it', async (t) => {
  const { root, loader, info, settle } = await cached(t);
  await settle();
  const runs = () => generateCalls(loader).length;

  await writeFile(join(root, 'data/one.json'), '{"n":2}');
  assert.equal((await settle()).outputs[0].status, 'stale');
  assert.equal(runs(), 2);

  await writeFile(join(root, 'data/two.json'), '{}');
  await settle();
  assert.equal(runs(), 3);

  await writeFile(join(root, 'gen/table.md'), '<!-- generated by block-beaver; do not edit -->\nhand edit\n');
  const repaired = await settle();
  assert.equal(repaired.outputs[0].status, 'stale');
  assert.equal(runs(), 4);

  info.closureHash = 'c2';
  await settle();
  assert.equal(runs(), 5);
  assert.equal((await settle()).outputs[0].status, 'cached');
});

test('an unreadable cache is an empty cache: no error, regenerated, and rewritten', async (t) => {
  for (const damaged of ['{not json', '[]', '{"schemaVersion":2,"entries":{}}', '{"schemaVersion":1,"entries":{"custom:gen/table.ts":"nope"}}', '']) {
    const { root, loader, settle } = await cached(t, { files: { 'data/one.json': '1', '.blocks/cache/generators.json': damaged } });
    const result = await settle();
    assert.deepEqual(result.diagnostics, [], damaged);
    assert.equal(result.outputs[0].status, 'missing');
    assert.equal(generateCalls(loader).length, 1);
    assert.equal(JSON.parse(await readFile(join(root, '.blocks/cache/generators.json'), 'utf8')).entries['custom:gen/table.ts'].inputsHash.length, 64);
  }
});

test('cache: false always runs, and gen --check neither reads a stale cache as fresh nor writes one', async (t) => {
  const uncached = await cached(t, { cache: false });
  await uncached.settle();
  await uncached.settle();
  assert.equal(generateCalls(uncached.loader).length, 2);
  assert.equal((await uncached.settle()).cacheUpdate, null);
  assert.ok(!(await listing(uncached.root)).includes('.blocks'), 'no cache file for uncached generators');

  const checked = await cached(t);
  const result = await plan(checked.root, checked.loader);
  assert.deepEqual(checkGeneration(result).map((item) => item.code), ['output-missing']);
  assert.ok(result.cacheUpdate, 'the plan knows what it would cache');
  assert.deepEqual(await listing(checked.root), ['data', 'data/one.json', 'docs', 'docs/readme.md'], 'check wrote neither output nor cache');
});

test('history is created, then left byte-identical until a manifest hash changes', async (t) => {
  const root = await repo(t);
  const state = { families: [family('gizmo', { generators: ['history'], registry: null })], manifests: [manifest('gizmo', 'a', { hash: 'sha256:aaa' })] };
  const first = await plan(root, fakeLoader(state), { now: new Date('2026-10-01T12:00:00.987Z') });
  assert.deepEqual(JSON.parse(first.outputs[0].expected), { schemaVersion: 1, entries: [{ date: '2026-10-01T12:00:00Z', label: null, source: 'gen', changes: [{ op: 'upsert', block: 'gizmo:a', hash: 'sha256:aaa' }] }] });
  await applyGeneration(root, first);
  const written = await readFile(join(root, '.blocks/history.json'), 'utf8');

  const again = await plan(root, fakeLoader(state), { now: new Date('2027-01-01T00:00:00Z') });
  assert.equal(again.outputs[0].status, 'fresh');
  assert.deepEqual(checkGeneration(again), []);
  assert.equal(again.outputs[0].expected, written);

  const changed = { families: state.families, manifests: [manifest('gizmo', 'a', { hash: 'sha256:bbb' }), manifest('gizmo', 'b', { hash: 'sha256:ccc' })] };
  const next = await plan(root, fakeLoader(changed), { now: new Date('2026-10-02T14:00:00+02:00'), label: 'cli label', config: { history: { label: 'configured' } } });
  assert.deepEqual(checkGeneration(next).map((item) => item.code), ['history-stale']);
  assert.equal(await readFile(join(root, '.blocks/history.json'), 'utf8'), written, 'check left history alone');
  const entry = JSON.parse(next.outputs[0].expected).entries[1];
  assert.deepEqual(entry, { date: '2026-10-02T12:00:00Z', label: 'cli label', source: 'gen', changes: [{ op: 'upsert', block: 'gizmo:a', hash: 'sha256:bbb' }, { op: 'upsert', block: 'gizmo:b', hash: 'sha256:ccc' }] });
  const configured = await plan(root, fakeLoader(changed), { now: NOW, config: { history: { label: 'configured' } } });
  assert.equal(JSON.parse(configured.outputs[0].expected).entries[1].label, 'configured');

  await applyGeneration(root, configured);
  const removed = await plan(root, fakeLoader({ families: state.families, manifests: [manifest('gizmo', 'b', { hash: 'sha256:ccc' })] }), { now: NOW });
  assert.deepEqual(JSON.parse(removed.outputs[0].expected).entries[2].changes, [{ op: 'delete', block: 'gizmo:a' }]);
});

test('a damaged history file is refused rather than overwritten', async (t) => {
  for (const text of ['{broken', '{"schemaVersion":2,"entries":[]}', '{"schemaVersion":1,"entries":[{"date":"yesterday","label":null,"source":"gen","changes":[]}]}']) {
    const root = await repo(t, { '.blocks/history.json': text });
    const result = await plan(root, fakeLoader({ families: [family('gizmo', { generators: ['history'], registry: null })], manifests: [manifest('gizmo', 'a')] }));
    assert.deepEqual(codes(result), ['output-conflict'], text);
    assert.deepEqual(result.outputs, []);
    assert.deepEqual((await applyGeneration(root, result)).written, []);
    assert.equal(await readFile(join(root, '.blocks/history.json'), 'utf8'), text);
  }
});

test('the loader is asked for custom generators only, and receives the graph, label and exact paths', async (t) => {
  const root = await repo(t);
  const graph = { nodes: [{ kind: 'file', path: 'src/a.ts', hash: 'h1' }, { kind: 'block', id: 'block:x:y' }] };
  const loader = fakeLoader({ generators: [custom('gen/x.ts', { out: 'gen/x.md', cache: false })], outputs: { 'custom:gen/x.ts': 'x' } });
  await plan(root, loader, { graph, paths: ['src/a.ts'], label: null, config: { history: { label: 'configured' } } });
  const [metadata, run] = loader.calls;
  assert.equal(metadata.generate, undefined);
  assert.deepEqual(metadata.paths, ['src/a.ts']);
  assert.deepEqual(metadata.fileHashes, { 'src/a.ts': 'h1' });
  assert.deepEqual(run.generate, { keys: ['custom:gen/x.ts'], graph, label: 'configured' });
});

test('cache freshness includes generator context while scan timestamps stay transient', async (t) => {
  const root = await repo(t, { 'data/one.json': '1' });
  let runs = 0;
  const state = { families: [], manifests: [], generators: [custom('gen/context.ts', { out: 'gen/context.md', inputs: ['data/*.json'] })] };
  const loader = fakeLoader({ ...state, outputs: { 'custom:gen/context.ts': () => `run ${++runs}` } });
  let config = {}, label = null, graph = { nodes: [], scannedAt: 'first' };
  const settle = async () => {
    const result = await plan(root, loader, { config, label, graph });
    assert.deepEqual(result.diagnostics, []);
    await applyGeneration(root, result);
    return result;
  };
  await settle();
  graph = { ...graph, scannedAt: 'second' };
  assert.equal((await settle()).outputs[0].status, 'cached');
  config = { custom: { title: 'new configuration' } };
  assert.equal((await settle()).outputs[0].status, 'stale');
  label = 'new label';
  assert.equal((await settle()).outputs[0].status, 'stale');
  graph = { ...graph, nodes: [{ kind: 'file', path: 'src/new.ts', hash: 'new' }] };
  assert.equal((await settle()).outputs[0].status, 'stale');
  state.manifests.push(manifest('gizmo', 'new'));
  assert.equal((await settle()).outputs[0].status, 'stale');
  assert.equal(runs, 5);
  assert.equal((await settle()).outputs[0].status, 'cached');
});

test('errors reported by the generation loader prevent every write', async (t) => {
  const root = await repo(t);
  const issue = { rule: 'manifest-valid', code: 'changed-during-load', severity: 'error', message: 'manifest changed' };
  const base = fakeLoader({ generators: [custom('gen/x.ts', { out: 'gen/x.md', cache: false })], outputs: { 'custom:gen/x.ts': 'valid output' } });
  const loader = async (args) => {
    const result = await base(args);
    return args.generate ? { ...result, diagnostics: [issue] } : result;
  };
  const result = await plan(root, loader);
  assert.deepEqual(result.diagnostics, [issue]);
  assert.deepEqual((await applyGeneration(root, result)).written, []);
  assert.deepEqual(await listing(root), []);
});

test('protected and reserved outputs remain protected on case-insensitive filesystems', async (t) => {
  const root = await repo(t);
  const outs = ['.blocks/CONFIG.json', '.GIT/new.ts', 'NODE_MODULES/new.ts', '.BLOCKS/CACHE/new.json', 'BLOCKS/GIZMOS/a.ts', 'BLOCKS/GIZMO.FAMILY.ts', '.CLAUDE/settings.json', '.codex/hooks.json', '.agents/generated.md', '.cursor/rules/generated.md', '.blocks/baseline.json', '.blocks/managed-files.json', '.blocks/install.json', '.blocks/WORKFLOW.md', '.blocks/view-exports.json', '.blocks/view/exports.json', 'GEN/SELF.ts'];
  const loader = fakeLoader({
    families: [family('gizmo', { generators: [] })], manifests: [manifest('gizmo', 'a')],
    generators: outs.map((out, index) => custom(index === outs.length - 1 ? 'gen/self.ts' : `gen/${index}.ts`, { out })),
  });
  const result = await plan(root, loader);
  assert.equal(result.diagnostics.length, outs.length);
  assert.ok(result.diagnostics.every((item) => item.code === 'output-unsafe'));
  assert.deepEqual(result.outputs, []);
  assert.equal(generateCalls(loader).length, 0);
});

// ---- stable generation: gen converges when outputs feed later outputs (#32) ----

async function realProject(t, generators) {
  const { symlink } = await import('node:fs/promises');
  const { fileURLToPath } = await import('node:url');
  const packageRoot = fileURLToPath(new URL('../', import.meta.url));
  const files = {
    'package.json': '{"name":"stable-gen","type":"module"}\n',
    '.blocks/config.json': JSON.stringify({ schemaVersion: 1, apps: [{ id: 'site', root: '.', entries: ['source/main.ts'] }],
      families: [{ id: 'unit', contract: 'definitions/unit.ts', manifests: 'catalog/*.entry.ts', registry: { out: 'generated/units.ts', exportName: 'units', importExtension: '.ts' } }],
      generators: Object.keys(generators) }),
    'definitions/unit.ts': `import { defineFamily, s } from 'block-beaver/kernel'; export default defineFamily({id:'unit',fields:s.object({}),implementation:['module'],generators:['registry']});\n`,
    'catalog/alpha.entry.ts': `export const alpha = {id:'alpha',family:'unit',version:1,name:'Alpha',description:'a',rationale:'r',implementation:{kind:'module',module:'../source/main.ts'}} as const;\n`,
    'source/main.ts': 'export const main = true;\n',
    ...generators,
  };
  const root = await repo(t, files);
  await mkdir(join(root, 'node_modules'), { recursive: true });
  await symlink(packageRoot, join(root, 'node_modules/block-beaver'), 'dir');
  return root;
}

test('a generator that imports the generated registry settles in one gen and gen --check is clean', async (t) => {
  const { generateProject } = await import('../src/families/commands.mjs');
  const root = await realProject(t, {
    'generators/count.ts': `import { defineGenerator } from 'block-beaver/kernel';
let count = -1;
try { count = (await import('../generated/units.ts')).units.all.length; } catch {}
export default defineGenerator({ out: 'generated/count.json', inputs: ['catalog/*.entry.ts'], generate() { return JSON.stringify({ count }); } });\n`,
  });
  const result = await generateProject(root, { now: NOW });
  assert.equal(result.ok, true, JSON.stringify(result));
  assert.ok(result.passes >= 2 && result.passes <= 3, `passes ${result.passes}`);
  assert.deepEqual(JSON.parse(await readFile(join(root, 'generated/count.json'), 'utf8')), { count: 1 });
  assert.ok(result.written.includes('generated/units.ts') && result.written.includes('generated/count.json'));
  const checked = await generateProject(root, { check: true, now: NOW });
  assert.equal(checked.ok, true, JSON.stringify(checked));
  assert.deepEqual(checked.pending, []);
  const again = await generateProject(root, { now: NOW });
  assert.deepEqual(again.written, []);
  assert.equal(again.passes, 1);
});

test('a generator that depends on its own previous output is reported as generator-unstable after three passes', async (t) => {
  const { generateProject } = await import('../src/families/commands.mjs');
  const root = await realProject(t, {
    'generators/osc.ts': `import { defineGenerator } from 'block-beaver/kernel';
import { readFileSync } from 'node:fs';
const file = new URL('../generated/osc.json', import.meta.url);
let n = 0;
try { n = JSON.parse(readFileSync(file, 'utf8')).n; } catch {}
export default defineGenerator({ out: 'generated/osc.json', inputs: ['catalog/*.entry.ts'], cache: false, generate() { return JSON.stringify({ n: n + 1 }); } });\n`,
  });
  const result = await generateProject(root, { now: NOW });
  assert.equal(result.ok, false);
  assert.equal(result.passes, 3);
  const unstable = result.diagnostics.find((item) => item.code === 'generator-unstable');
  assert.ok(unstable, JSON.stringify(result.diagnostics));
  assert.equal(unstable.rule, 'family-drift');
  assert.equal(unstable.severity, 'error');
  assert.deepEqual(unstable.files, ['generated/osc.json']);
  assert.match(unstable.message, /generated\/osc\.json/);
  assert.equal(JSON.parse(await readFile(join(root, 'generated/osc.json'), 'utf8')).n, 3);
  assert.ok(result.written.includes('generated/osc.json'));
});

test('gen --check and --dry-run stay single-plan and read-only', async (t) => {
  const { generateProject } = await import('../src/families/commands.mjs');
  const root = await realProject(t, {});
  for (const mode of [{ check: true }, { dryRun: true }]) {
    const result = await generateProject(root, { ...mode, now: NOW });
    assert.deepEqual(result.written, []);
    assert.equal(result.passes, undefined);
  }
  assert.equal((await readdir(root)).includes('generated'), false);
});
