import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm, symlink, cp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { generateProject } from '../src/families/commands.mjs';
import { scanRepository } from '../src/scanner.mjs';
import { attachProjectRegistry } from '../src/adapter.mjs';
import { updateProject } from '../src/block-map.mjs';

test('an existing named manifest adopts families unchanged and keeps registry semantics and embedded view checks', async (t) => {
  const root = await mkdtemp(join(tmpdir(), 'beaver-adoption-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const packageRoot = fileURLToPath(new URL('../', import.meta.url));
  const write = async (path, content) => { await mkdir(dirname(join(root, path)), { recursive: true }); await writeFile(join(root, path), content); };
  await mkdir(join(root, 'node_modules'), { recursive: true });
  await symlink(packageRoot, join(root, 'node_modules/block-beaver'), 'dir');
  await write('package.json', '{"name":"existing-project","type":"module"}\n');
  await write('.blocks/config.json', JSON.stringify({ schemaVersion: 1, apps: [{ id: 'site', root: '.', entries: ['source/main.ts'] }], families: [{ id: 'unit', contract: 'definitions/unit.ts', manifests: 'catalog/*.entry.ts', registry: { out: 'generated/units.ts', exportName: 'units', importExtension: '.ts' } }], generators: ['generators/summary.ts'], history: { label: 'Adopted' } }));
  await write('definitions/unit.ts', `import { defineFamily, s } from 'block-beaver/kernel'; export default defineFamily({id:'unit',fields:s.object({tag:s.string()}),implementation:['module'],generators:['registry','index','history']});\n`);
  await write('generators/summary.ts', `import { defineGenerator } from 'block-beaver/kernel'; export default defineGenerator({out:'generated/summary.json',inputs:['catalog/*.entry.ts'],generate(ctx){ if(!Object.isFrozen(ctx.graph)||!Object.isFrozen(ctx.manifests('unit')[0])) throw Error('mutable'); return JSON.stringify({names:ctx.manifests('unit').map(m=>m.name),label:ctx.label}); }});\n`);
  const authored = `export const alpha = {id:'alpha',family:'unit',version:1,name:'Alpha',description:'Existing manifest',rationale:'Keep the existing boundary',implementation:{kind:'module',module:'../source/main.ts'},tag:'green'} as const;\n`;
  await write('catalog/alpha.entry.ts', authored);
  await write('source/main.ts', 'export const main = true;\n');
  const cli = (...args) => JSON.parse(execFileSync(process.execPath, [join(packageRoot, 'bin/block-beaver.mjs'), ...args, '--root', root], { encoding: 'utf8' }));
  const before = await attachProjectRegistry(await scanRepository(root, { writeConfig: false }));
  assert.equal(before.familyDiagnostics.length, 0, JSON.stringify(before.familyDiagnostics));
  assert.ok(before.edges.some((edge) => edge.from === 'block:unit:alpha' && edge.to === 'file:source/main.ts' && edge.kind === 'implemented-by'));
  const generated = await generateProject(root, { now: '2026-10-01T12:00:00Z' });
  assert.equal(generated.ok, true, JSON.stringify(generated));
  assert.equal(await readFile(join(root, 'catalog/alpha.entry.ts'), 'utf8'), authored);
  assert.deepEqual(JSON.parse(await readFile(join(root, 'generated/summary.json'), 'utf8')), { names: ['Alpha'], label: 'Adopted' });
  const runtime = JSON.parse(execFileSync(process.execPath, ['--input-type=module', '-e', `const {units}=await import('./generated/units.ts');console.log(JSON.stringify({family:units.family,ids:units.all.map(m=>m.id),tag:units.get('alpha').tag,frozen:Object.isFrozen(units.all)}));`], { cwd: root, encoding: 'utf8' }));
  assert.deepEqual(runtime, { family: 'unit', ids: ['alpha'], tag: 'green', frozen: true });
  assert.ok(Array.isArray(JSON.parse(await readFile(join(root, '.blocks/index.json'), 'utf8'))));
  const history = await readFile(join(root, '.blocks/history.json'), 'utf8');
  assert.deepEqual((await generateProject(root)).written, []);
  assert.equal(await readFile(join(root, '.blocks/history.json'), 'utf8'), history);
  assert.equal(cli('kit', 'list').result.blocks[0].graphId, 'block:unit:alpha');
  cli('view', '--format', 'module', '--out', 'embedded.mjs');
  assert.equal(cli('gen', '--check').ok, true);
  await write('catalog/alpha.entry.ts', authored.replace("name:'Alpha'", "name:'Updated alpha'"));
  const stale = await generateProject(root, { check: true });
  assert.equal(stale.ok, false);
  assert.ok(stale.pending.includes('embedded.mjs'));
  await generateProject(root);
  await updateProject(root);
  assert.equal(cli('gen', '--check').ok, true);
  const clone = await mkdtemp(join(tmpdir(), 'differently-named-clone-'));
  t.after(() => rm(clone, { recursive: true, force: true }));
  await cp(root, clone, { recursive: true, verbatimSymlinks: true });
  const clonedCheck = await generateProject(clone, { check: true });
  assert.equal(clonedCheck.ok, true, JSON.stringify(clonedCheck));
});
