import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateProject } from '../src/families/commands.mjs';

const NOW = new Date('2026-10-01T12:00:00Z');
const cli = fileURLToPath(new URL('../bin/block-beaver.mjs', import.meta.url));
const packageRoot = fileURLToPath(new URL('../', import.meta.url));
const tokensBody = "export const tokens = ['a', 'b'] as const;\n";
const manifestOf = (id, tone) => `export const ${id}Unit = {id:'${id}',family:'unit',version:1,name:'${id}',description:'d',rationale:'r',implementation:{kind:'module',module:'../source/main.ts'},tone:'${tone}'} as const;\n`;

/** A real project whose contract imports a generator's output at load time. */
async function project(t, { files = {}, config = {} } = {}) {
  const root = await mkdtemp(join(tmpdir(), 'block-beaver-adopt-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const all = {
    'package.json': '{"name":"adopt","type":"module"}\n',
    '.blocks/config.json': JSON.stringify({ schemaVersion: 1, apps: [{ id: 'site', root: '.', entries: ['source/main.ts'] }],
      families: [{ id: 'unit', contract: 'definitions/unit.ts', manifests: 'catalog/*.entry.ts', registry: { out: 'generated/units.ts', exportName: 'units', importExtension: '.ts' } }],
      generators: ['generators/tokens.ts'], ...config }),
    'definitions/unit.ts': `import { defineFamily, s } from 'block-beaver/kernel';\nimport { tokens } from '../generated/tokens.ts';\nexport default defineFamily({id:'unit',fields:s.object({tone:s.enum(tokens)}),implementation:['module'],generators:['registry']});\n`,
    'generators/tokens.ts': `import { defineGenerator } from 'block-beaver/kernel';\nexport default defineGenerator({ out: 'generated/tokens.ts', inputs: ['catalog/*.entry.ts'], generate: () => ${JSON.stringify(tokensBody)} });\n`,
    'generated/tokens.ts': tokensBody,
    'catalog/alpha.entry.ts': manifestOf('alpha', 'a'),
    'catalog/beta.entry.ts': manifestOf('beta', 'b'),
    'source/main.ts': 'export const main = true;\n',
    ...files,
  };
  for (const [path, text] of Object.entries(all)) {
    if (text === null) continue;
    await mkdir(dirname(join(root, path)), { recursive: true });
    await writeFile(join(root, path), text);
  }
  await mkdir(join(root, 'node_modules'), { recursive: true });
  await symlink(packageRoot, join(root, 'node_modules/block-beaver'), 'dir');
  return root;
}

const read = (root, path) => readFile(join(root, path), 'utf8');
const exists = async (root, path) => { try { await read(root, path); return true; } catch { return false; } };
const codes = (result) => result.diagnostics.map((item) => item.code);
const run = (root, ...args) => spawnSync(process.execPath, [cli, ...args, '--root', root], { encoding: 'utf8' });

test('without --adopt a headerless output a contract imports stays an output-conflict and nothing is written', async (t) => {
  const root = await project(t);
  const result = await generateProject(root, { now: NOW });
  assert.equal(result.ok, false);
  assert.deepEqual(codes(result), ['output-conflict']);
  assert.equal(result.diagnostics[0].file, 'generated/tokens.ts');
  assert.equal(await read(root, 'generated/tokens.ts'), tokensBody);
  assert.equal(await exists(root, 'generated/units.ts'), false);
});

test('gen --adopt PATH takes over a load-time output without deleting it, and gen --check is then clean', async (t) => {
  const root = await project(t);
  const result = await generateProject(root, { now: NOW, adopt: ['generated/tokens.ts'] });
  assert.equal(result.ok, true, JSON.stringify(result.diagnostics));
  assert.deepEqual(result.outputs.find((output) => output.out === 'generated/tokens.ts'), { key: 'custom:generators/tokens.ts', out: 'generated/tokens.ts', status: 'adopted', bodyIdentical: true });
  assert.ok(result.written.includes('generated/tokens.ts') && result.written.includes('generated/units.ts'));
  assert.equal(await read(root, 'generated/tokens.ts'), `// generated by block-beaver from catalog/*.entry.ts; do not edit\n${tokensBody}`);
  const checked = await generateProject(root, { check: true, now: NOW });
  assert.equal(checked.ok, true, JSON.stringify(checked.diagnostics));
  assert.deepEqual(checked.pending, []);
  assert.ok(checked.outputs.every((output) => output.status === 'fresh' || output.status === 'cached'));
  const again = await generateProject(root, { now: NOW, adopt: ['generated/tokens.ts'] });
  assert.equal(again.ok, true, 'Adopting an output that is already generated is a no-op.');
  assert.deepEqual(again.written, []);
});

test('gen --adopt --dry-run writes nothing and reports whether the bodies match', async (t) => {
  for (const [body, identical] of [[tokensBody, true], ["export const tokens = ['a', 'b', 'c'] as const;\n", false]]) {
    const root = await project(t, { files: { 'generated/tokens.ts': body } });
    const result = await generateProject(root, { now: NOW, dryRun: true, adopt: true });
    assert.equal(result.ok, true, JSON.stringify(result.diagnostics));
    assert.deepEqual(result.written, []);
    assert.deepEqual(result.outputs.find((output) => output.out === 'generated/tokens.ts'), { key: 'custom:generators/tokens.ts', out: 'generated/tokens.ts', status: 'adopted', bodyIdentical: identical });
    assert.ok(result.pending.includes('generated/tokens.ts'));
    assert.equal(await read(root, 'generated/tokens.ts'), body);
    assert.equal(await exists(root, 'generated/units.ts'), false);
    assert.equal(await exists(root, '.blocks/cache/generators.json'), false);
  }
});

test('deleting an output that a contract imports reports output-required-for-load naming both files', async (t) => {
  const root = await project(t, { files: { 'generated/tokens.ts': null } });
  const result = await generateProject(root, { now: NOW });
  assert.equal(result.ok, false);
  const item = result.diagnostics.find((entry) => entry.code === 'output-required-for-load');
  assert.ok(item, JSON.stringify(result.diagnostics));
  assert.equal(codes(result).includes('unresolved-import'), false);
  assert.deepEqual([item.severity, item.file, item.output], ['error', 'definitions/unit.ts', 'generated/tokens.ts']);
  assert.match(item.message, /definitions\/unit\.ts/);
  assert.match(item.message, /git restore generated\/tokens\.ts/);
  assert.match(item.message, /gen --adopt generated\/tokens\.ts/);
  const checked = await generateProject(root, { check: true, now: NOW });
  assert.ok(codes(checked).includes('output-required-for-load'));
  assert.equal(await exists(root, 'generated/units.ts'), false);
});

test('a missing import that no generator claims stays unresolved-import', async (t) => {
  const root = await project(t, { files: { 'generated/tokens.ts': null, 'generators/tokens.ts': `import { defineGenerator } from 'block-beaver/kernel';\nexport default defineGenerator({ out: 'generated/other.ts', inputs: ['catalog/*.entry.ts'], generate: () => '' });\n` } });
  const result = await generateProject(root, { now: NOW });
  assert.ok(codes(result).includes('unresolved-import'), JSON.stringify(result.diagnostics));
  assert.equal(codes(result).includes('output-required-for-load'), false);
});

test('a check module that imports a deleted registry or a cache-recorded output gets output-required-for-load', async (t) => {
  const computed = `import { defineGenerator } from 'block-beaver/kernel';\nconst name = 'computed';\nexport default defineGenerator({ out: \`generated/\${name}.ts\`, inputs: ['catalog/*.entry.ts'], generate: () => 'export const computed = 1;' });\n`;
  const root = await project(t, { files: { 'generators/computed.ts': computed, 'checks/units.ts': `import { units } from '../generated/units.ts';\nimport { computed } from '../generated/computed';\nexport default () => units.all.length && computed ? [] : [{ message: 'empty' }];\n` },
    config: { generators: ['generators/tokens.ts', 'generators/computed.ts'] } });
  assert.equal((await generateProject(root, { now: NOW, adopt: ['generated/tokens.ts'] })).ok, true);
  const config = JSON.parse(await read(root, '.blocks/config.json'));
  await writeFile(join(root, '.blocks/config.json'), JSON.stringify({ ...config, checks: ['checks/units.ts'] }));
  assert.equal((await generateProject(root, { now: NOW })).ok, true);
  assert.equal(JSON.parse(await read(root, '.blocks/cache/generators.json')).entries['custom:generators/computed.ts'].out, 'generated/computed.ts');
  const registryText = await read(root, 'generated/units.ts');
  await rm(join(root, 'generated/units.ts'));
  const registry = await generateProject(root, { check: true, now: NOW });
  const missing = registry.diagnostics.filter((item) => item.code === 'output-required-for-load');
  assert.deepEqual(missing.map((item) => [item.rule, item.file, item.output]), [['family-valid', 'checks/units.ts', 'generated/units.ts']], JSON.stringify(registry.diagnostics));
  assert.equal((await generateProject(root, { now: NOW })).ok, false, 'gen cannot recreate an output that loading needs.');
  await writeFile(join(root, 'generated/units.ts'), registryText);
  await rm(join(root, 'generated/computed.ts'));
  const recorded = await generateProject(root, { check: true, now: NOW });
  assert.deepEqual(recorded.diagnostics.filter((item) => item.code === 'output-required-for-load').map((item) => item.output), ['generated/computed.ts'], JSON.stringify(recorded.diagnostics));
  await rm(join(root, '.blocks/cache/generators.json'));
  const unrecorded = await generateProject(root, { check: true, now: NOW });
  assert.ok(codes(unrecorded).includes('unresolved-import'), 'Without a literal out or a cache record the output is not statically known.');
  assert.equal(codes(unrecorded).includes('output-required-for-load'), false);
});

test('the CLI adopts listed paths relative to the root and refuses --check with --adopt', async (t) => {
  const root = await project(t);
  const refused = run(root, 'gen', '--check', '--adopt', 'generated/tokens.ts');
  assert.equal(refused.status, 1);
  assert.match(refused.stderr, /--check never adopts/);
  const stray = run(root, 'gen', 'generated/tokens.ts');
  assert.equal(stray.status, 1);
  assert.match(stray.stderr, /--adopt/);
  const outside = run(root, 'gen', '--adopt', '../elsewhere.ts');
  assert.equal(outside.status, 1);
  assert.equal(await read(root, 'generated/tokens.ts'), tokensBody);
  const unclaimed = run(root, 'gen', '--adopt', 'generated/nothing.ts');
  assert.equal(unclaimed.status, 2);
  assert.ok(JSON.parse(unclaimed.stdout).diagnostics.some((item) => item.code === 'adopt-not-claimed' && item.file === 'generated/nothing.ts'));
  const adopted = run(root, 'gen', '--adopt', './generated/../generated/tokens.ts');
  assert.equal(adopted.status, 0, adopted.stdout + adopted.stderr);
  assert.match(await read(root, 'generated/tokens.ts'), /^\/\/ generated by block-beaver/);
  assert.equal(run(root, 'gen', '--check').status, 0);
});

test('adopting a registered view module settles across passes without adopt-not-claimed', async (t) => {
  const root = await project(t, { files: { '.blocks/view-exports.json': '[{"path":"generated/view.ts","format":"module"}]\n', 'generated/view.ts': 'export const BLOCK_BEAVER_VIEW = {};\n' } });
  const refused = await generateProject(root, { now: NOW, adopt: ['generated/tokens.ts'] });
  assert.deepEqual(codes(refused), ['output-conflict']);
  assert.equal(refused.diagnostics[0].file, 'generated/view.ts');
  const result = await generateProject(root, { now: NOW, adopt: ['generated/tokens.ts', 'generated/view.ts'] });
  assert.equal(result.ok, true, JSON.stringify(result.diagnostics));
  assert.ok(result.passes >= 2, `passes ${result.passes}`);
  assert.equal(result.outputs.find((output) => output.out === 'generated/view.ts').status, 'adopted');
  assert.match(await read(root, 'generated/view.ts'), /^\/\/ generated by block-beaver from the project graph; do not edit\nexport const BLOCK_BEAVER_VIEW = "/);
  assert.equal((await generateProject(root, { check: true, now: NOW })).ok, true);
});

test('a tsconfig alias import of a deleted output gets output-required-for-load', async (t) => {
  const root = await project(t, { files: {
    'tsconfig.json': '{"compilerOptions":{"module":"esnext","moduleResolution":"bundler","allowImportingTsExtensions":true,"noEmit":true,"baseUrl":".","paths":{"@generated/*":["generated/*"]}}}\n',
    'definitions/unit.ts': `import { defineFamily, s } from 'block-beaver/kernel';\nimport { tokens } from '@generated/tokens';\nexport default defineFamily({id:'unit',fields:s.object({tone:s.enum(tokens)}),implementation:['module'],generators:['registry']});\n`,
  }, config: { apps: [{ id: 'site', root: '.', tsconfig: 'tsconfig.json', entries: ['source/main.ts'] }] } });
  const adopted = await generateProject(root, { now: NOW, adopt: ['generated/tokens.ts'] });
  assert.equal(adopted.ok, true, JSON.stringify(adopted.diagnostics));
  await rm(join(root, 'generated/tokens.ts'));
  const result = await generateProject(root, { check: true, now: NOW });
  const item = result.diagnostics.find((entry) => entry.code === 'output-required-for-load');
  assert.ok(item, JSON.stringify(result.diagnostics));
  assert.deepEqual([item.file, item.output], ['definitions/unit.ts', 'generated/tokens.ts']);
  assert.equal(codes(result).includes('unresolved-import'), false);
});

test('a cache entry for a generator that is no longer configured does not claim its old output', async (t) => {
  const computed = `import { defineGenerator } from 'block-beaver/kernel';\nconst name = 'computed';\nexport default defineGenerator({ out: \`generated/\${name}.ts\`, inputs: ['catalog/*.entry.ts'], generate: () => 'export const computed = 1;' });\n`;
  const root = await project(t, { files: { 'generators/computed.ts': computed, 'checks/computed.ts': `import { computed } from '../generated/computed.ts';\nexport default () => computed ? [] : [{ message: 'missing' }];\n` },
    config: { generators: ['generators/tokens.ts', 'generators/computed.ts'] } });
  assert.equal((await generateProject(root, { now: NOW, adopt: ['generated/tokens.ts'] })).ok, true);
  const config = JSON.parse(await read(root, '.blocks/config.json'));
  await writeFile(join(root, '.blocks/config.json'), JSON.stringify({ ...config, generators: ['generators/tokens.ts'], checks: ['checks/computed.ts'] }));
  assert.equal(JSON.parse(await read(root, '.blocks/cache/generators.json')).entries['custom:generators/computed.ts'].out, 'generated/computed.ts');
  await rm(join(root, 'generated/computed.ts'));
  const result = await generateProject(root, { check: true, now: NOW });
  assert.ok(result.diagnostics.some((item) => item.code === 'unresolved-import' && item.file === 'checks/computed.ts'), JSON.stringify(result.diagnostics));
  assert.equal(codes(result).includes('output-required-for-load'), false);
});
