import { posix } from 'node:path';
import { readProjectFile, writeProjectFiles } from '../project-files.mjs';
import { indexPath, renderIndex, renderRegistry } from './builtin-generators.mjs';
import { cachePath, hashInputs, inputsHash, outputHash, readCache, serializeCache } from './cache.mjs';
import { isFamilyPath } from './config.mjs';
import { discoverFiles, matchGlobs } from './glob.mjs';
import { appendHistory, historyPath, readHistory, serializeHistory } from './history.mjs';
import { clashesOf, composeRegions, readRegion, regionBody, regionStyle, regionStyles } from './regions.mjs';

const lineComment = new Set(['.ts', '.tsx', '.mts', '.cts', '.js', '.jsx', '.mjs', '.cjs']);
const htmlComment = new Set(['.md', '.html']);
const generatedHeader = /^\s*(?:\/\/|\/\*|<!--)[^\n]*generated by block-beaver/i;
// Line breaks, including the Unicode separators, would end a // comment early.
const lineBreaks = new RegExp(`[\\r\\n${String.fromCharCode(0x2028, 0x2029)}]+`, 'g');

/** Emission order and config field paths follow config.families, never the map floor. */
const configIndexOf = (family) => family.configIndex ?? family.floor ?? 0;
const extensionOf = (path) => posix.extname(path).toLowerCase();
const headerStyle = (path) => (lineComment.has(extensionOf(path)) ? 'line' : extensionOf(path) === '.css' ? 'block' : htmlComment.has(extensionOf(path)) ? 'html' : extensionOf(path) === '.json' ? 'none' : null);
const problem = (code, message, extra = {}) => ({ rule: code === 'registry-out-missing' ? 'config-valid' : 'family-drift', code, severity: 'error', message, ...extra });

/** A glob such as `a/**` + `/*.ts` contains the comment terminator, and `--` is illegal in HTML comments. */
function headerFor(style, inputs) {
  const from = inputs.length ? ` from ${inputs.join(', ')}` : '';
  const text = `generated by block-beaver${from}; do not edit`.replace(lineBreaks, ' ');
  if (style === 'line') return `// ${text}`;
  if (style === 'block') return `/* ${text.replaceAll('*/', '*\\/')} */`;
  return `<!-- ${text.replaceAll('--', '-\\-')} -->`;
}

/** LF endings and a trailing newline; headers are the runner's job, and JSON stays valid and bare. */
function finalize(out, content, inputs) {
  if (typeof content !== 'string') throw problem('generator-failed', `Output ${out} must be a string`, { file: out });
  let body = content.replace(/\r\n?/g, '\n');
  if (body !== '' && !body.endsWith('\n')) body += '\n';
  const style = headerStyle(out);
  if (style === 'none') {
    try { JSON.parse(body); } catch (error) { throw problem('generator-failed', `Output ${out} is not valid JSON: ${error.message}`, { file: out }); }
    return body;
  }
  const header = headerFor(style, inputs);
  return body === '' ? `${header}\n` : `${header}\n${body}`;
}

const toDate = (now) => {
  const date = now === undefined ? new Date() : now instanceof Date ? now : new Date(now);
  if (Number.isNaN(date.getTime())) throw new TypeError('planGeneration needs a valid now');
  return date;
};

const fileHashesOf = (graph) => Object.fromEntries((graph?.nodes ?? []).filter((node) => node.kind === 'file' && node.hash).map((node) => [node.path, node.hash]));

async function safeRead(root, path) {
  try { return { text: await readProjectFile(root, path) }; }
  catch (error) { return { error }; }
}

function unsafeReason(claim, protectedPaths) {
  if (!isFamilyPath(claim.out)) return 'is not a safe repository-relative path';
  const folded = claim.out.toLowerCase();
  if (protectedPaths.has(folded)) return 'would overwrite a manifest, contract, generator or config file';
  if (folded.split('/').some((part) => ['.claude', '.codex', '.agents', '.cursor'].includes(part))) return 'is inside an agent guidance location';
  if (folded.split('/').some((part) => part === '.git' || part === 'node_modules') || folded.startsWith('.blocks/cache/')) return 'is inside a reserved location';
  if (claim.region) return regionStyle(claim.out) ? null : `has no region marker style (${regionStyles})`;
  if (headerStyle(claim.out) === null) return 'has no supported header style (.ts .js .css .md .html .json)';
  return null;
}

/**
 * Decide every generated output without touching the disk. Order is fixed: registries in
 * family order, index, family generators, top-level generators, extra outputs, history.
 */
export async function planGeneration({ root, config = {}, graph, paths, label = null, now, extraOutputs = [], loadFamilies } = {}) {
  const stamp = toDate(now);
  const load = loadFamilies ?? (await import('./loader.mjs')).loadFamilies;
  const base = { root, config, paths, fileHashes: fileHashesOf(graph), ...(graph?.resolutionSignature ? { resolutionSignature: graph.resolutionSignature } : {}) };
  const loaded = await load(base);
  const diagnostics = [...(loaded.diagnostics ?? [])];
  const families = [...(loaded.families ?? [])].sort((a, b) => configIndexOf(a) - configIndexOf(b));
  const manifests = loaded.manifests ?? [];
  const resolvedLabel = label ?? config?.history?.label ?? null;
  // Everything exposed by ctx can affect the result, even when it is not a
  // matched input file. A scan's wall-clock timestamp is not project state.
  const { scannedAt: _scannedAt, ...stableGraph } = graph ?? {};
  const generationContext = { config, label: resolvedLabel, graph: stableGraph,
    families, manifests: manifests.map((item) => ({ family: item.family, id: item.id, hash: item.hash, value: item.value })) };
  const asks = (kind) => families.some((family) => family.generators?.includes(kind));

  // 1. Claims, in the fixed order.
  const claims = [];
  for (const family of families.filter((item) => item.generators?.includes('registry'))) {
    const out = family.config?.registry?.out;
    if (!out) { diagnostics.push(problem('registry-out-missing', `Family ${family.id} asks for a registry but sets no registry.out`, { file: '.blocks/config.json', family: family.id, field: `$.families[${configIndexOf(family)}].registry.out` })); continue; }
    claims.push({ key: `registry:${family.id}`, kind: 'registry', out, family, familyId: family.id, inputs: [family.config.manifests] });
  }
  if (asks('index')) claims.push({ key: 'index', kind: 'index', out: indexPath, inputs: [] });
  const customs = (loaded.generators ?? []).filter((info) => info.source === 'custom');
  const known = new Set(families.map((family) => family.id));
  const customClaim = (info) => ({ key: info.key, kind: 'custom', out: info.out, ...(info.region ? { region: info.region } : {}), info, familyId: info.family, inputs: info.inputs });
  for (const family of families) claims.push(...customs.filter((info) => info.family === family.id).map(customClaim));
  claims.push(...customs.filter((info) => !info.family || !known.has(info.family)).map(customClaim));
  for (const extra of extraOutputs) claims.push({ key: extra.key, kind: 'extra', out: extra.out, extra, inputs: extra.inputs ?? [] });
  if (asks('history')) claims.push({ key: 'history', kind: 'history', out: historyPath, inputs: [] });

  // 2. Reject unsafe outputs, then collisions, before any generator runs.
  const protectedPaths = new Set(['.blocks/config.json', '.blocks/WORKFLOW.md', '.blocks/managed-files.json', '.blocks/install.json', '.blocks/baseline.json', '.blocks/view-exports.json', '.blocks/view/exports.json', '.github/copilot-instructions.md', cachePath, ...manifests.map((item) => item.path), ...families.map((family) => family.config?.contract), ...customs.map((info) => info.path), ...(Array.isArray(config?.checks) ? config.checks.filter(isFamilyPath) : [])].filter(Boolean).map((path) => path.toLowerCase()));
  const safe = [];
  for (const claim of claims) {
    const reason = unsafeReason(claim, protectedPaths);
    if (reason) diagnostics.push(problem('output-unsafe', `${claim.key} output ${JSON.stringify(claim.out)} ${reason}`, { ...(typeof claim.out === 'string' ? { file: claim.out } : {}), ...(claim.familyId ? { family: claim.familyId } : {}) }));
    else safe.push(claim);
  }
  const byOut = new Map();
  for (const claim of safe) {
    const slot = claim.out.toLowerCase();
    byOut.set(slot, [...(byOut.get(slot) ?? []), claim]);
  }
  const colliding = new Set();
  for (const group of byOut.values()) {
    for (const clash of clashesOf(group)) {
      for (const claim of clash) colliding.add(claim);
      const region = clash.every((claim) => claim.region === clash[0].region) && clash[0].region;
      diagnostics.push(problem('output-collision', `${clash.map((claim) => claim.key).join(' and ')} all write ${clash[0].out}${region ? ` region ${region}` : ''}`, { file: clash[0].out }));
    }
  }
  const accepted = safe.filter((claim) => !colliding.has(claim));

  // 3. Current bytes on disk for everything still in play.
  const currents = new Map(), regionTexts = new Map();
  const readable = [];
  for (const claim of accepted) {
    const read = await safeRead(root, claim.out);
    if (read.error) diagnostics.push(problem('output-unsafe', `Cannot read ${claim.out}: ${read.error.message}`, { file: claim.out }));
    else if (claim.region) {
      // A region claim's current value is its body; the whole text is kept for splicing.
      const found = readRegion(read.text, claim);
      if (found.problem) diagnostics.push(problem(found.problem.code, found.problem.message, { file: claim.out, ...(claim.familyId ? { family: claim.familyId } : {}) }));
      else { currents.set(claim.key, found.body); regionTexts.set(claim.key, read.text); readable.push(claim); }
    } else { currents.set(claim.key, read.text); readable.push(claim); }
  }

  // 4. Custom generators: skip those whose inputs, code and output are unchanged.
  const cacheRead = await safeRead(root, cachePath);
  const cache = readCache(cacheRead.text);
  const wanted = readable.filter((claim) => claim.kind === 'custom');
  const cacheable = wanted.filter((claim) => claim.info.cache !== false);
  const hashes = new Map();
  if (cacheable.length && !cacheRead.error) {
    const files = [...new Set([...(await discoverFiles(root)), ...(paths ?? [])])];
    for (const claim of cacheable) {
      const matched = matchGlobs(files, claim.info.inputs);
      hashes.set(claim.key, inputsHash({ closureHash: claim.info.closureHash, out: claim.out, inputs: await hashInputs(root, matched), context: generationContext }));
    }
  }
  const skipped = new Set(cacheable.filter((claim) => {
    const entry = cache.entries[claim.key], current = currents.get(claim.key);
    return hashes.has(claim.key) && entry?.inputsHash === hashes.get(claim.key) && current !== null && entry.outHash === outputHash(current);
  }).map((claim) => claim.key));
  const toRun = wanted.filter((claim) => !skipped.has(claim.key)).map((claim) => claim.key);
  const generated = new Map();
  if (toRun.length) {
    const result = await load({ ...base, generate: { keys: toRun, graph, label: resolvedLabel } });
    for (const output of result.outputs ?? []) generated.set(output.key, output);
    const outputDiagnostics = new Set((result.outputs ?? []).filter((output) => output.diagnostic).map((output) => JSON.stringify(output.diagnostic)));
    for (const item of result.diagnostics ?? []) {
      if (!outputDiagnostics.has(JSON.stringify(item)) && !diagnostics.some((existing) => JSON.stringify(existing) === JSON.stringify(item))) diagnostics.push(item);
    }
  }

  // 5. Render every output in claim order.
  const outputs = [];
  const settled = new Map(), regionResults = [];
  for (const claim of readable) {
    const current = currents.get(claim.key);
    let expected;
    try {
      if (claim.kind === 'custom') {
        if (claim.region && skipped.has(claim.key)) { regionResults.push({ claim, body: current, status: 'cached' }); settled.set(claim.key, current); continue; }
        if (skipped.has(claim.key)) { outputs.push({ key: claim.key, out: claim.out, expected: current, current, status: 'cached' }); settled.set(claim.key, current); continue; }
        const result = generated.get(claim.key);
        if (!result) throw problem('generator-failed', `Generator ${claim.key} produced no output`, { file: claim.info.path });
        if (result.diagnostic) { diagnostics.push(result.diagnostic); continue; }
        if (claim.region) {
          const made = regionBody(claim, result.content);
          if (made.problem) throw problem(made.problem.code, made.problem.message, { file: claim.info.path, ...(claim.familyId ? { family: claim.familyId } : {}) });
          expected = made.body;
        } else expected = finalize(claim.out, result.content, claim.inputs);
      } else if (claim.kind === 'registry') {
        expected = finalize(claim.out, renderRegistry({ family: claim.family, manifests: manifests.filter((item) => item.family === claim.family.id) }), claim.inputs);
      } else if (claim.kind === 'index') {
        expected = finalize(claim.out, renderIndex({ families, manifests }), claim.inputs);
      } else if (claim.kind === 'extra') {
        expected = finalize(claim.out, await claim.extra.render(), claim.inputs);
      } else {
        let doc;
        try { doc = readHistory(current); }
        catch (error) { throw problem('output-conflict', `${historyPath} cannot be extended: ${error.message}`, { file: historyPath }); }
        const appended = appendHistory(doc, new Map(manifests.map((item) => [item.ref, item.hash])), { label: resolvedLabel, now: stamp });
        // An unchanged history keeps its exact bytes.
        expected = appended.changed || current === null || current.trim() === '' ? serializeHistory(appended.doc) : current;
      }
    } catch (error) {
      diagnostics.push(error?.rule ? error : problem('generator-failed', `${claim.key} failed: ${error?.message ?? error}`, { file: claim.out, ...(claim.familyId ? { family: claim.familyId } : {}) }));
      continue;
    }
    if (claim.region) { regionResults.push({ claim, body: expected, status: current === expected ? 'fresh' : 'stale' }); settled.set(claim.key, expected); continue; }
    let status;
    if (current === null) status = 'missing';
    else if (current === expected) status = 'fresh';
    else if (headerStyle(claim.out) !== 'none' && !generatedHeader.test(current)) {
      status = 'conflict';
      diagnostics.push(problem('output-conflict', `${claim.out} exists and was not generated by block-beaver; refusing to overwrite it`, { file: claim.out }));
    } else status = 'stale';
    outputs.push({ key: claim.key, out: claim.out, expected, current, status });
    if (claim.kind === 'custom' && status !== 'conflict') settled.set(claim.key, expected);
  }
  outputs.push(...composeRegions(regionResults, regionTexts));

  // 6. Cache entries for the custom generators that produced a trustworthy output.
  let cacheUpdate = null;
  if (!cacheRead.error) {
    const entries = {};
    for (const claim of cacheable) if (settled.has(claim.key) && hashes.has(claim.key)) entries[claim.key] = { inputsHash: hashes.get(claim.key), outHash: outputHash(settled.get(claim.key)) };
    const content = serializeCache(entries);
    if (content !== cacheRead.text && (cacheRead.text !== null || Object.keys(entries).length)) cacheUpdate = { path: cachePath, before: cacheRead.text, content };
  }
  return { outputs, diagnostics, cacheUpdate };
}

/** Write stale and missing outputs (and the cache) through the safe writer; refuse on any error. */
export async function applyGeneration(root, plan) {
  if (plan.diagnostics.some((item) => item.severity === 'error')) return { written: [], diagnostics: plan.diagnostics };
  const files = plan.outputs.filter((item) => item.status === 'stale' || item.status === 'missing').map((item) => ({ path: item.out, before: item.current, content: item.expected }));
  if (plan.cacheUpdate) files.push({ path: plan.cacheUpdate.path, before: plan.cacheUpdate.before, content: plan.cacheUpdate.content });
  try {
    const changed = await writeProjectFiles(root, files);
    return { written: changed.filter((path) => path !== cachePath), diagnostics: plan.diagnostics };
  } catch (error) {
    return { written: [], diagnostics: [...plan.diagnostics, problem('output-conflict', error.message)] };
  }
}

/** Report drift without writing anything, the cache included. */
export function checkGeneration(plan) {
  const drift = [];
  for (const output of plan.outputs) {
    if (output.status !== 'missing' && output.status !== 'stale') continue;
    if (output.regions) {
      for (const item of output.regions.filter((entry) => entry.status === 'stale')) drift.push(problem('output-stale', `${output.out} region ${item.region} is out of date; run block-beaver gen`, { file: output.out, region: item.region }));
      continue;
    }
    const code = output.key === 'history' ? 'history-stale' : output.status === 'missing' ? 'output-missing' : 'output-stale';
    drift.push(problem(code, `${output.out} is ${output.status === 'missing' ? 'missing' : 'out of date'}; run block-beaver gen`, { file: output.out, ...(output.key.startsWith('registry:') ? { family: output.key.slice('registry:'.length) } : {}) }));
  }
  return [...plan.diagnostics, ...drift];
}

/** Outputs a plan would still write. */
export const changedOutputs = (plan) => plan.outputs.filter((item) => item.status === 'stale' || item.status === 'missing').map((item) => item.out);

/** Generation kept changing its own inputs; name the files still changing on the last pass. */
export const generatorUnstable = (files, passes) => problem('generator-unstable',
  `Generation did not settle after ${passes} passes; still changing: ${files.join(', ')}. A manifest or generator output depends on its own previous output.`,
  { file: files[0], files });
