import { readProjectFile } from './project-files.mjs';
import { renderBlockMap } from './block-map.mjs';

export const viewModuleHeader = '// generated by block-beaver from the project graph; do not edit\n';
export const viewDetails = ['full', 'map'];
/** A registry entry or option without `detail` is full detail; anything else must be a known level. */
export const validViewDetail = (detail) => detail === undefined || viewDetails.includes(detail);
export const renderViewModuleBody = (graph, { detail = 'full' } = {}) => `export const BLOCK_BEAVER_VIEW = ${JSON.stringify(renderBlockMap(graph, detail === 'full' ? {} : { detail }))};\n`;
export const renderViewModule = (graph, options) => viewModuleHeader + renderViewModuleBody(graph, options);

/** Registered module exports participate in generation and read-only drift checks. */
export async function registeredViewOutputs(root, graph) {
  const text = await readProjectFile(root, '.blocks/view-exports.json') ?? await readProjectFile(root, '.blocks/view/exports.json');
  if (text === null) return [];
  const entries = JSON.parse(text);
  if (!Array.isArray(entries)) throw new Error('Invalid generated view exports registry.');
  return entries.map((entry) => {
    if (entry?.format !== 'module' || typeof entry.path !== 'string' || !entry.path || entry.path.startsWith('/') || entry.path.includes('\\') || entry.path.split('/').some((part) => !part || part === '.' || part === '..')) throw new Error('Invalid generated view module path.');
    if (!validViewDetail(entry.detail)) throw new Error('Invalid generated view module detail.');
    return { key: `view:${entry.path}`, out: entry.path, detail: entry.detail ?? 'full', inputs: ['the project graph'], render: () => renderViewModuleBody(graph, { detail: entry.detail }) };
  });
}
